export { Hero } from "./Hero/Hero";
export { EventDetailsExtended } from "./EventDetailsExtended/EventDetailsExtended";
export { Registration } from "./Registration/Registration";
export { About } from "./About/About";
export { Location } from "./Location/Location";
export { FAQ } from "./FAQ/FAQ";
export { Schedule } from "./Schedule/Schedule";
export { SchedulePlaceholder } from "./Schedule/SchedulePlaceholder";
export { Partners } from "./Partners/Partners";
