name: Linting
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: ESLint
        run: npm run eslint
      - name: StyleLint
        run: npm run stylelint